name: robust_ps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=1.4.0=py39h06a4308_0
  - aiohttp=3.8.5=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39h06a4308_0
  - attrs=23.1.0=py39h06a4308_0
  - blas=1.0=mkl
  - blinker=1.6.2=py39h06a4308_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - contourpy=1.0.5=py39hdb19cb5_0
  - cryptography=41.0.3=py39hdda0065_0
  - cudatoolkit=11.3.1=hb98b00a_12
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=hef1e5e3_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.0=py39h5eee18b_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=2.22.0=py39h06a4308_0
  - google-auth-oauthlib=0.5.2=py39h06a4308_0
  - grpc-cpp=1.48.2=he1ff14a_3
  - grpcio=1.48.2=py39he1ff14a_3
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtest=1.14.0=hdb19cb5_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - importlib_resources=6.1.0=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h0b41bf4_3
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20221030=h5eee18b_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.39=h753d276_0
  - libpq=12.15=hdbd6064_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsqlite=3.44.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=17.0.4=h4dfa4b3_0
  - llvmlite=0.43.0=py39h6a678d5_1
  - markdown=3.4.1=py39h06a4308_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.8.0=py39h06a4308_0
  - matplotlib-base=3.8.0=py39h1128e8f_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - multidict=6.0.2=py39h5eee18b_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h59595ed_2
  - nettle=3.6=he412f7d_0
  - numba=0.60.0=py39h0320e7d_0
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - oauthlib=3.2.2=py39h06a4308_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.4=hd590300_0
  - packaging=23.1=py39h06a4308_0
  - pcre=8.45=h295c915_0
  - pillow=10.0.1=py39ha6cbd5a_0
  - pip=23.3.1=pyhd8ed1ab_0
  - platformdirs=3.10.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - pooch=1.7.0=py39h06a4308_0
  - protobuf=3.20.3=py39h6a678d5_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39h06a4308_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h0755675_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=4_cp39
  - pytorch=1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py39h06a4308_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - qt-main=5.15.2=h7358343_9
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=py39h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.3.0=py39h1128e8f_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - tabulate=0.8.10=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.12.1=py39h06a4308_0
  - tensorboard-data-server=0.7.0=py39h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py39h06a4308_0
  - torchaudio=0.10.1=py39_cu113
  - torchvision=0.11.2=py39_cu113
  - tornado=6.3.3=py39h5eee18b_0
  - tqdm=4.65.0=py39hb070fc8_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=1.26.18=py39h06a4308_0
  - werkzeug=2.2.3=py39h06a4308_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yacs=0.1.6=pyhd3eb1b0_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py39h5eee18b_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - albumentations==1.3.1
      - et-xmlfile==2.0.0
      - imageio==2.37.0
      - lazy-loader==0.4
      - networkx==3.2.1
      - opencv-python-headless==4.8.1.78
      - openpyxl==3.1.5
      - pywavelets==1.6.0
      - qudida==0.0.4
      - scikit-image==0.19.3
      - scipy==1.10.1
      - setuptools==59.5.0
      - tifffile==2024.8.30